dist: xenial
sudo: required

language: python
cache: pip

before_install:
  - sudo apt install rabbitmq-server
addons:
  apt:
    update: true

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install .[dev]

script:
  - py.test

jobs:
  include:
    - stage: docs-test
      python: 3.6
      install:
          - pip install .[dev,docs]
      script:
          - sphinx-build -nT -b dummy docs/source build/html
