dist: bionic
language: python
cache: pip

addons:
  apt:
    packages:
      - rabbitmq-server

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install .[dev]
  # - pip install -U git+https://github.com/aiidateam/kiwipy.git@develop

script:
  - py.test

jobs:
  include:
    - stage: docs-test
      python: 3.6
      install:
          - pip install .[dev,docs]
      script:
          - sphinx-build -nT -b dummy docs/source build/html
