dist: xenial
sudo: required

language: python
cache: pip

before_install:
  - sudo apt install rabbitmq-server
addons:
  apt:
    update: true

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install .[dev]

script:
  - py.test
