language: python
cache: pip

services:
  - rabbitmq

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -e git+https://github.com/muhrin/apricotpy.git@develop#egg=apricotpy
  - pip install .[rmq]

script:
  - py.test
